### ISSUE TITLE
FA icon classes

### ISSUE THREAD

**Issue by ciar4n** [C-Lodder/lightning#16]
https://github.com/joomla/joomla-cms/pull/28351

**Comment by C-Lodder** [comment]
Yup, keeping track of this closely. Hopefully gets merged

**Comment by C-Lodder** [comment]
Temporarily added until Joomla supports inline SVGs: https://github.com/C-Lodder/lightning/commit/0a7e58b84133fcbb58c5eceb185d1aa2524b84f3
