### ISSUE TITLE
Custom css partially working

### ISSUE THREAD

**Issue by Razerr** [C-Lodder/lightning#231]
Tried a plugin that loads custom.css in the header to make some small css changes. They appear everywhere except for the article pages. Although the custom CSS appears in the header too.

Could be a theme issue or a plugin issue? Calling the file manually in header ( index.php) doesn't seem to work. Thank you for any help. The theme is awesome.

**Comment by C-Lodder** [comment]
Hi @Razerr,

Could you share the code from the plugin please, so I can test?

Maybe also add the CSS you're trying to load .

**Comment by Razerr** [comment]
@C-Lodder Don't remember exactly the plugin source but I know the download was fron Github. In the meantime I found [this one ](https://extensions.joomla.org/extension/add-custom-css/) and works as expected.

The main reason I decided to use Joomla for a personal/blogging site was your theme. The speed is quite impresive :)

**Comment by C-Lodder** [comment]
Ah good good.
It could have been a bug with the other plugin.
Am I ok to close this issue?

Glad you like the template :)

**Comment by Razerr** [comment]
Yes, issue solved :)
