### ISSUE TITLE
Main menu flashing on page reload

### ISSUE THREAD

**Issue by Razerr** [C-Lodder/lightning#232]
Working on my site noticed a strange thing regarding main menu. On page opening/ reload for 1-2 seconds menu items appear first vertical, unstyled, then normal. Making for an unpleasant flash. Like this https://ibb.co/sPLPH5d

I don't know if there is something with the theme or on my side. Had JCH Optimize installed, disabled it and  the issue is still present.

**Comment by C-Lodder** [comment]
The menu styling uses its own CSS file which is loaded via the mod_menu layout override.
I will probably need to apply this as critical CSS to prevent any FOUC with it.

**Comment by Razerr** [comment]
@C-Lodder Had 2 issues with the menu. Dropdowns not showing when the parent item is a separator. Fixed with little CSS. And the flashing of the menu wich I could't solve myself. I also got a warning in Gtmetrix regarding that.

**Comment by C-Lodder** [comment]
Thanks. I'll also fix the separator bug you mentioned too

**Comment by Razerr** [comment]
@C-Lodder Did you found something regarding main menu FOUC? As I am advancing with my site setup and your theme I'd be more confident to know if a fix will come. :)

**Comment by C-Lodder** [comment]
Could you try installing this please?
[tpl_lightning-v1.0.0.zip](https://github.com/C-Lodder/lightning/files/7277392/tpl_lightning-v1.0.0.zip)

It will hopefully help with the FOUC on the menu

**Comment by Razerr** [comment]
@C-Lodder FOUC is not vissible anymore. I guess that solves the problem :)

**Comment by C-Lodder** [comment]
I've released v1.1.0 which also fixes the separator menu dropdown bug: https://github.com/C-Lodder/lightning/releases/tag/v1.1.0

Thank you for reporting the issues.
