### ISSUE TITLE
Joomla 4 no longer installing correctly 

### ISSUE THREAD

**Issue by M4dKiwi** [C-Lodder/lightning#237]
Hi - love the template ,however it seems the latest comit may have affected things?
(for fresh new install via Joomla4 extentions manager) it now gives the following error ...

JInstaller: :Install: File does not exist C:\xampp\htdocs\Joomla\tmp\install_6159972661c38\lightning-master\css
Template Install: Could not copy files from the files source.
×
danger
Error installing plugin

![image](https://user-images.githubusercontent.com/22867564/135752541-eed57f32-b2c3-46b2-9af3-9795048eb370.png)
(above similar error also when manually unziping directly in Joomla 4 tmp folder )

**Comment by C-Lodder** [comment]
Thanks for the report. I'll take a look at this tomorrow morning

**Comment by M4dKiwi** [comment]
shoot , you had me worried there (my mistake sending you my latest attempts - admittedly I am a learner ) but I've been trying a few differnt methods but was getting the same results ...... this time trying again with correct path 

![image](https://user-images.githubusercontent.com/22867564/135758579-32356951-74dc-4f54-a6a5-a597abb49016.png)

I have succesfully installed this template to another local joomla site of mine no problem a week ago 
,so I wonder if there has been any recent changes since then that have may affected the install?
Thanks for your reply & thanks for the template - Im loving the hiq custom ccs options

**Comment by M4dKiwi** [comment]
I did not mean to close this issue, but I hope its error on my part
(I have made a copy of my other joomla sites lightning folder but had to paste it into a diff template folder which as you can see worked but its not as perfect as a proper joomla template install - so it may be worth having a look at)
![image](https://user-images.githubusercontent.com/22867564/135760375-61113f1b-9986-4790-869a-925534ec4e8b.png)

**Comment by C-Lodder** [comment]
I can't replicate the issue. I'm able to install the latest xip file on a fresh installation of Joomla 4.
Can you explain how you're trying to install the template?

**Comment by M4dKiwi** [comment]
How strange ,I'm hoping its user error - I have tried several diff methods ,
the latest ( * 5 mins ago & the usual way I use) was a the simple drag
(lightning-1.0.0.zip)  from my downloads
into the joomla admins extensions manager / upload package file but
unfortunately same result ....

[image: image.png]
I will try shortly a fresh install & hopefully that does the
if so I will close this ticket  & I'm sorry if  I've wasted your time,

however I also have the same issue that is still open
(flashing menu list items then 2 seconds later it comes right)
I'm hoping there may be a way to have the header menu style preloaded
first (not sure if this only happens when/if also loading the custom hiq
colors)
- this will hopefully be a quick few lines of code tweek which I would
share if I solve it myself

Thanks for the reply & will update you on the fresh install results asap
(its now 8:30 NZ time so I will do this  a.s.a.p after I get my kids to bed
(& can think in peace! - it might be another all nighter for me))

**Comment by C-Lodder** [comment]
I've just noticed from your screenshot the error says `Error installing plugin`.

Are you trying to install the sample data plugin or the actual template?

**Comment by M4dKiwi** [comment]
I am trying to install the original template
 ( I have 2 versions of Joomla 4 & 1 of Joomla 3+ - a week ago I installed
the lightning template successfully on one of them)
(via git url upload)  however the 2nd Joomla4 site had problems installing
the same template this week via
the zip file, via the url & via the /tmp folder but they all get the same
error message.

I just tried a fresh install of Joomla4  (my copy was Joomla 4.1 & I then
updated it via the joomla version updates option
then I uploaded lightning-1.0.0.zip into the joomla4 Extensions  Install
but agin same error
[image: image.png]
Im not sure what has changed between my experience in the last 8+ days
between my first successful install & the second not.
I may have only updated the latest version of Joomla AFTER  (I had
previously)  installed  lightning  template successfully on site #1
& since I have tried installing the template on J4 site #2 but this this
after  updating to the latest Joomla4 version
(Im wondering since (I think) there has been no changes to lightning-1.0.0)
that maybe its a Joomla4 issue affecting it
 - if so ,  1,000 apologies or else I'm hoping my feedback would solve this
& make this template keep being awesome.

*I'm now officially stumped ,if this is just user error on my part I'm
embarrassed as well as confused. *
*I don't know why I can't replicate the smooth template install again (&/or
in the future when I host my site offsite) *

*feel free to close this issue if thats the case - in which case I look
forward to the flickering menu navbar issue to be resolved *
*so that at least my local Joomla4 site #1 continues to look great using
the lightning-1.0.0 template    *

I can use this to do a rough patch fix for any future J4 sites if I keep
getting this issue (which I showed in a pic earlier)
via FTP + copying site#1's (configured/customised) lightning template files
into (replacing) the new sites default template folder.

which looks horrible (+is unconfigurable) in Site Template styles
(I think due to the schema, json / XML files not also being uploaded into
sql database?) ,anyway its rough as guts but does work
(but easiest way to configure the template custom ccs visually through
Joomla4 site#1 each time (or good old notepad))

**Comment by C-Lodder** [comment]
> Im not sure what has changed between my experience in the last 8+ days between my first successful install & the second not

v1.0.0 of lightning was released 28 days ago and no code changes have been made (other than dependency updates) since then.

If you're not developing on your local machine and would like to provide me a link to your site, along with some admin credentials (admin[at]joomjunk.co.uk), I can try and look into the issue for you.

I'll close this for now, as I cannot replicate the issue.
