### ISSUE TITLE
(sub) Menu Styling 

### ISSUE THREAD

**Issue by M4dKiwi** [C-Lodder/lightning#242]
Hi I have been trying to solve this problem. but have had little success
basicly I am wanting to add a gradient using the --hiq-ccs format into the menu navbar (via the user.css) 
but I'd assumed the dropdown menu background color was set via the ---hiq-dropdown-background-color custom options
however it doesnt seem to effect the dropdown background color at all.
I have also (using the Joomla menu item edit) set the template style to Lightning on the details tab 
![image](https://user-images.githubusercontent.com/22867564/136731289-3be56980-d35e-4110-a41b-777a4d9f749c.png)
(I love the Dark themed backend template too by the way :) )
it still apears that the submenu items are not picking up on the lightning  C:\xampp\htdocs\4Joomla\templates\lightning\css\mod_menumenu.min.css style settings. 
on inspection of the front end it seems the drop down class comes under the 'unstyled' Joomla Menu Mod class 
  ( ul class="mod-menu__sub list-unstyled small" )
I'm a little fustrated as I can add a new menu module but I'd rather not ,it just seems I'm having trouble getting my submenu to gell with the lightning mod_menu menu.css (using overide of user.css of course) .
Its totally possible this is not an error in your template, more likely something I'm not doing right on the Joomla backend,
do you have any suggestions or tips on how to fix this or what Im doing wrong here?
Thanks - Sharn

**Comment by C-Lodder** [comment]
In your `user.css`, you can use the following for a gradient in submenus:
```
.navbar-menu .mod-menu__sub {
  background: linear-gradient(90deg, rgb(0, 255, 16) 0%, rgb(255, 0, 0) 100%);
}
```

![image](https://user-images.githubusercontent.com/2019801/136734490-da48c327-9284-4886-8612-f6db58f79fbd.png)
