### ISSUE TITLE
An error has occurred.  0 syntax error, unexpected 

### ISSUE THREAD

**Issue by ftlx** [C-Lodder/lightning#248]
Hi C-Lodder

Thanks for your quick reply.

Please the screenshot with system debug enabled.

Regards
FTLX

![Screenshot 2021-11-01 at 11-20-52 Error 0](https://user-images.githubusercontent.com/93517522/139657235-004a6693-0a15-42fc-96ba-e0755b633b2d.png)

**Comment by ftlx** [comment]
Hi C-Lodder

I think problem is solved.. my PHP ver. was 7.2 and after changing to 7.3 the error is no longer there.
Thanks for a great template  :-)

**Comment by C-Lodder** [comment]
Ahh I see the error now.

PHP 7.3 added support for trailing commas in function calls, so this explains why it was throwing an error on PHP 7.2

I'll fix this in the next update

**Comment by C-Lodder** [comment]
Fixed here: https://github.com/C-Lodder/lightning/commit/f2fcdf9e23fccc47adae11dcf18fec3415226102
