### ISSUE TITLE
Styling issues on Google cache

### ISSUE THREAD

**Issue by Razerr** [C-Lodder/lightning#268]
Not shure if the looks of my cached website by Google has any importance but, though, noticed an isue regarding that. Everything occupies only a small part othe left of the screen. If I delete **display: grid;** from **.site-grid{}** in browser console everything looks almost as should. Thanks for any help regarding this.

**Comment by C-Lodder** [comment]
Have you tried clearing your browser cache?

**Comment by Razerr** [comment]
Yes. Maybe the grid system conflicts with how google interprets template css. I don't know :/ Here's [a screenshot 
](https://ibb.co/TMX3LjQ)

Deleting **display: grid;** from **.site-grid{}** gives an webpage missing some styling but it shows full screen, as should.

**Comment by C-Lodder** [comment]
Would you be able to provide a link to your site?

**Comment by Razerr** [comment]
@C-Lodder if it helps shorturl.at/sCKRT

**Comment by C-Lodder** [comment]
URL not working for me. Where are you seeing this issue? On your actual site, or some indexed screenshot taken by Google?

**Comment by Razerr** [comment]
When I search my site on google and click the arrow next to the link: view page in cache

**Comment by C-Lodder** [comment]
That's nothing to do with the template

**Comment by Razerr** [comment]
Well, since the template is free, nothing to do more on that. Google cache it's not probably that important anywhay.
