### ISSUE TITLE
Missing main content on the hompage after 1.2 update

### ISSUE THREAD

**Issue by Razerr** [C-Lodder/lightning#270]
After 1.2 update main content on the homepage is gone. I have set my home page to show Featured Articles template. Previewed module positions and I have main-top, breadcrumbs and main-bottom. No content in between.

**Comment by C-Lodder** [comment]
In the template settings, you should see a "Hide Component" option.
Is this set to `Yes` or `No` for you?

**Comment by Razerr** [comment]
It was set to No. But now switching to Yes then No againg gave me the main content displayed. 

One thing, though, prior the update I had customized that part template to have non-leading articles display in columns and now I get them stacked as my customization is not available anymore.

**Comment by C-Lodder** [comment]
> I had customized that part template
How exactly did you customise it?

**Comment by C-Lodder** [comment]
I've fixed the issue you were having with the main content being hidden on the homepage: https://github.com/C-Lodder/lightning/commit/47f9b29877b1ca630c271bc9db7a26b06801e3df

**Comment by Razerr** [comment]
@C-Lodder Problem completelly solved. First of all by default after the update "Hide component" is set to No but after your firs reply I switched the option to Yes then No again and it worked. Second I got back my home layout with leading articles stacked and intro articles in columns by adding a CSS class in menu > homepage > blog layout option and some CSS.

Thanks!
