### ISSUE TITLE
Finish French translations

### ISSUE THREAD

**Issue by C-Lodder** [C-Lodder/lightning#275]
https://github.com/C-Lodder/lightning/blob/master/language/fr-FR/fr-FR.tpl_lightning.ini

**Comment by MATsxm** [comment]
I will don't worry ;)

**Comment by MATsxm** [comment]
Still have to work on sampledata ;)

**Comment by MATsxm** [comment]
I guess it's ok now?
Let me know if you need other fr-FR ;)

**Comment by C-Lodder** [comment]
Thank you so much!
