### ISSUE TITLE
Missing API key

### ISSUE THREAD

**Issue by mariantanase** [C-Lodder/lightning#280]
When open Template style, it show an error (see pic), and no style on frontpage .
Is there a link where I can see a demo ?

![missing-api-key](https://user-images.githubusercontent.com/3976174/150333288-c6d632f4-f7cb-4d78-a1fa-d490c6c784e2.png)

**Comment by C-Lodder** [comment]
Hi @mariantanase,

That error is because it's missing the API Key for Google Fonts, which you can find on the Advanced tab.
I should probably stop showing that error an a global alert and show it inline, next to the field.

**Comment by C-Lodder** [comment]
Hi @mariantanase 

If you'd like to see a demo, you can go here: https://demo.joomjunk.co.uk/

I've fixed the error alert always being displayed here: https://github.com/C-Lodder/lightning/commit/ce4991639c7d29cb78789216ce8b2723a2fbd7a4
