### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by C-Lodder** [C-Lodder/lightning#3]
- [x] Base dark theme
- [x] Add support for `prefers-color-scheme` which will be used as the default if the `theme` if undefined in the localstorage.
- [ ] Still a fair few variables that need tweaking for dark theme

**Comment by AndyGaskell** [comment]
Looks great, like the top right toggle

**Comment by nikosdion** [comment]
I see two issues with the switcher. More of a wishlist than issues.

1. If you manually set a theme you cannot go back to automatic selection without clearing local storage. This is not a very user friendly approach. I would prefer it if the switcher was tri-state with the default state being "auto".
1. When my browser changes from light to dark or vice versa the site remains in the light/dark state it loaded with. I do not know of a _good_ way to fix this with JavaScript. I imagine there must be a better way than setting an interval timer every 1-2 seconds to check the browser preference.

Should I file issues about them or should I go away quietly? :smiley:

**Comment by C-Lodder** [comment]
Thanks Nic, I'll add a "system preference" (middle) state to the toggle

**Comment by C-Lodder** [comment]
PR: https://github.com/C-Lodder/lightning/pull/77

Closing this for now. If any additional aspects of the page are missing their respective dark colours, separate issues can be opened.
