### ISSUE TITLE
`float: inline-start` only supported by FF

### ISSUE THREAD

**Issue by ciar4n** [C-Lodder/lightning#34]
https://github.com/C-Lodder/lightning/blob/920bfd1bee9e106e56e1a1ef46c8eca127b2e30b/src/css/utility/float.css

Ref: https://caniuse.com/#feat=mdn-css_properties_float_flow_relative_values

**Comment by C-Lodder** [comment]
Damn, that's not good.

**Comment by C-Lodder** [comment]
reverted back to standard properties
