### ISSUE TITLE
Set light theme as default

### ISSUE THREAD

**Issue by MyWay** [C-Lodder/lightning#359]
Hi, how can we set light theme as default?

**Comment by C-Lodder** [comment]
Hi @MyWay 
The theme is user preference. If they want to set the light theme as default, thy need to flick the switch in the top-right corner, like so:

![image](https://user-images.githubusercontent.com/2019801/196333077-0d2b6fe7-ed2d-4403-95ce-7e77cfa5f1a6.png)

**Comment by MyWay** [comment]
Hi, thanks for your answer. I wanted to set light at start for everybody, then they are free to switch to dark and get their preference saved.

**Comment by C-Lodder** [comment]
By default, the switcher is set to the middle. This will use the theme defined by in the user's operating system.
If their OS theme is set to `light`, then the website will be light.

If you wish to force light mode, even if the OS theme is set to `dark`, then you'll need to make some code changes.
