### ISSUE TITLE
Hardcoded strings in CSS overides tab

### ISSUE THREAD

**Issue by dcsjapan** [C-Lodder/lightning#390]
The table headers in `/fields/css.php` are hardcoded and so can't be translated.

I'll be happy to add Japanese translations if you'd care to put them in the language file.

---
Peripherally related issue:

You might consider removing the prefixes (e.g. `en-GB.` etc.)  from the filenames of the language files, as Joomla has done with Cassiopeia (presumably because the folder is namespacing enough).

PS: I can make this change and PR it if you like. But I'd better leave the string extraction to you as my PHP is very shaky.

**Comment by C-Lodder** [comment]
Thanks @dcsjapan. I will make these changes on Monday when I have some free time.

**Comment by dcsjapan** [comment]
No problem. Incidentally, I noticed something else after writing the above.

I don't know how concerned you are about consistency in string names, but if that sort of thing matters ...

`TPL_LIGHTNING_FIELDSET_ABOUT_VERSION`
`TPL_LIGHTNING_FIELDSET_ABOUT_REPORT_BUG`

are fields, not field sets, so they should probably be

`TPL_LIGHTNING_ABOUT_VERSION`
`TPL_LIGHTNING_ABOUT_REPORT_BUG`

**Comment by C-Lodder** [comment]
Thank you, I've now fixed this in the last couple of commits.
