### ISSUE TITLE
Module Positioning all over the place  

### ISSUE THREAD

**Issue by M4dKiwi** [C-Lodder/lightning#396]
Hi There 
I used this template a few years ago & it worked great, 
a lot of improvements since including improved Joomla 
so after installing the latest Joomla & Lightning template 
as well as sample data, it no longer looks as good as it did 
![image](https://user-images.githubusercontent.com/22867564/225814424-7ae74987-be3e-43ac-9989-ec206c922466.png)
was the 20/20 logo not included now in the zip file? - is that what's thrown the positioning out?
It used to look like the picture below after being at this stage (which was fantastic)
![image](https://user-images.githubusercontent.com/22867564/225814803-33a23f87-0275-44b2-85c5-9a165b79667a.png)

**Comment by C-Lodder** [comment]
Hi @M4dKiwi, did you install the lightning sample data plugin too?
Can you also let me know what versnio of Joomla and browser you're using?

**Comment by M4dKiwi** [comment]
ahhh ha , that was the issue, was using the Joomla sample data 
thank you, I've fixed the problem 
you've always been great at keeping in touch & improving the template 
loving it!  - can close this now 
SOLVED !
