### ISSUE TITLE
Dropdowns

### ISSUE THREAD

**Issue by deltapapa01** [C-Lodder/lightning#6]
Hi,
very nice, fast and simple template. Is there also the possibility to use menu dropdowns?

**Comment by C-Lodder** [comment]
Sure. Will hopefully do today :)

**Comment by C-Lodder** [comment]
Added in https://github.com/C-Lodder/lightning/commit/8be8d6e4cd2d14da0d5faa1029a645cc71bba914

Example markup:
```
<div class="dropdown">
  <button class="dropdown-toggle" type="button">Dropdown Toggle</button>
  <div class="dropdown-menu">
    <div class="dropdown-header">Dropdown header</div>
    <a href="#">Action</a>
    <a href="#">Another action</a>
    <div class="dropdown-divider"></div>
    <a href="#">Something else here</a>
  </div>
</div>
```

Tried to keep it in line with Bootstrap's markup.

Bare in mind I've only added basic CSS for this. It doesn't support:

- Right or center aligned dropdown
- Dropup
- Viewport detection

I was hoping that Joomla would have added the dropdown custom element by now which would have its own markup and CSS.
