### ISSUE TITLE
Lightning: Template doesn't install on Joomla 4-Beta-2

### ISSUE THREAD

**Issue by dautrich** [C-Lodder/lightning#66]
Downloaded the template from here and tried to install on freshly installed J! 4Beta2.
Template doesn't install (s. attachment).

![Screenshot_2020-07-02 Extensions Install - Dorfchronik Neudorf - Administration](https://user-images.githubusercontent.com/7933215/86403972-048efd80-bcaf-11ea-96f2-8d9a2e22ba7e.png)

**Comment by C-Lodder** [comment]
Hi @dautrich, I don't store the compiled CSS and JS on the repository to avoid conflicts, do you won't be able to download the repo itself. Please install the latest release from here: https://github.com/C-Lodder/lightning/releases/tag/v0.0.11
