### ISSUE TITLE
Show switcher does not work

### ISSUE THREAD

**Issue by nikosdion** [C-Lodder/lightning#75]
You have the following code in your templateDetails.xml:
```xml
				<field
					name="theme-switcher"
					type="radio"
					layout="joomla.form.field.radio.switcher"
					default="1"
					label="TPL_LIGHTNING_THEME_SWITCHER_LABEL"
					>
					<option value="true">JNO</option>
					<option value="false">JYES</option>
				</field>
```
This does not do what you think it does. The "true" and "false" values are strings, not booleans. As a result, the both evaluate to boolean `true` when you typecast them to boolean in PHP. Even if that wasn't the case the logic is inverted.

The correct code is:
```xml
				<field
					name="theme-switcher"
					type="radio"
					layout="joomla.form.field.radio.switcher"
					default="1"
					label="TPL_LIGHTNING_THEME_SWITCHER_LABEL"
					>
					<option value="0">JNO</option>
					<option value="1">JYES</option>
				</field>
```
Typecasting string 0 to boolean yields boolean `false` and typecasting string 1 to boolean yields boolean `true` which is what you were trying to do.

**Comment by C-Lodder** [comment]
Closing as you fixed this in: https://github.com/C-Lodder/lightning/pull/76
