### ISSUE TITLE
Font Awesome 5 Icons - not loaded - are they supported?

### ISSUE THREAD

**Issue by PhocaCz** [C-Lodder/lightning#80]
Hi, testing now version 0.0.13.

When I use Cassiopea, font awesome icons are displayed:

![fa displayed](https://i.imgur.com/jnXjdBY.png)

When I switch to lightning, they are not rendered:

![fa not displayed](https://i.imgur.com/YQ7eV6G.png)

Are Font Awesome Icons version 5 supported?

**Comment by C-Lodder** [comment]
Hey. If you have a look in the following directories, you'll find the FA fonts and you can load them from there:

> media\vendor\fontawesome-free\css
> media\vendor\fontawesome-free\webfonts

**Comment by C-Lodder** [comment]
Ignore the previous comment. Joomla's shipped version of FA doesn't include the `@font-face { ... }` statements and instead have done it in Atum, meaning they're pretty much expecting every other template to do the same.

I want to have a think about this before I do anything.

Loading FA would assist extension devs, however not loading may hopefully get them to think about using SVGs

**Comment by PhocaCz** [comment]
Ok, thank your for the info.

**Comment by N6REJ** [comment]
@C-Lodder
>Ignore the previous comment. Joomla's shipped version of FA doesn't include the @font-face { ... } statements and instead have done it in Atum, meaning they're pretty much expecting every other template to do the same.
 thats not still true is it?

**Comment by C-Lodder** [comment]
@N6REJ not sure. I haven't done much Joomla stuff for the last few months. May get some time over the holidays to take another look

**Comment by C-Lodder** [comment]
@PhocaCz What class are you using for the icons? `icon-xxx` or `fa-xxx`?

**Comment by PhocaCz** [comment]
fa-xxx

**Comment by C-Lodder** [comment]
@PhocaCz Can you try the latest zip please? 
[tpl_lightning-v0.0.13.zip](https://github.com/C-Lodder/lightning/files/5834022/tpl_lightning-v0.0.13.zip)

**Comment by PhocaCz** [comment]
Hi, no icons, I get following errors in JS console:

![img](https://i.imgur.com/MpOqZ9G.png)

The fonts are stores on my test website here:

media\vendor\fontawesome-free\webfonts\fa-solid-900.woff2

**Comment by C-Lodder** [comment]
Ahh sorry, you're right. The XML was missing the webfonts directory.
Try this one.
[tpl_lightning-v0.0.14-TEST-2.zip](https://github.com/C-Lodder/lightning/files/5840386/tpl_lightning-v0.0.14-TEST-2.zip)

**Comment by PhocaCz** [comment]
Now, I get the icons displayed:

![img](https://i.imgur.com/xe4akeb.png)

but still one error there:
![img](https://i.imgur.com/aQvIivY.png)

The link does not have the first folder:
Is:
localhost/media/vendor/fontawesome-free/webfonts/fa-solid-900.woff2
should be:
localhost/J4B6/media/vendor/fontawesome-free/webfonts/fa-solid-900.woff2

Not sure if this comes from core or template but I don't get this error when using Atum

**Comment by C-Lodder** [comment]
I'm not using this file `localhost/media/vendor/fontawesome-free/webfonts/fa-solid-900.woff2`. I load my own copy of FontAwesome in the Lightning template.

**Comment by PhocaCz** [comment]
Ok, I will try to find out which part is loading it.

Thank you.

**Comment by PhocaCz** [comment]
Not sure, if this part is loaded, but see image:

![img](https://i.imgur.com/IyQc69s.png)

**Comment by C-Lodder** [comment]
Yeah just saw I forgot to remove some old code :)

**Comment by C-Lodder** [comment]
[tpl_lightning-v0.0.14-TEST-3.zip](https://github.com/C-Lodder/lightning/files/5842762/tpl_lightning-v0.0.14-TEST-3.zip)

**Comment by PhocaCz** [comment]
No, everything is Ok on my test site. Thank you.

**Comment by C-Lodder** [comment]
Perfect.

Just a reminder that this will only support the `fa-xxx` classes. Using `icon-xxx` like Joomla has done a lot of in core, will not work.
Hopefully Joomla will stop using these stupid classes.
